main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id 
from main.views import register
from main.views import login_user
from main.views import logout_user, increment_amount, decrement_amount, delete_product
from main.views import edit_product, get_product_json, add_product_ajax, create_product_flutter



app_name = 'main'

urlpatterns = [
    
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('increment-amount/<int:id>/', increment_amount, name='increment_amount'),
    path('decrement-amount/<int:id>/', decrement_amount, name='decrement_amount'),
    path('delete-product/<int:id>/', delete_product, name='delete_product'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

setupin/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('auth/', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    price = models.IntegerField()
    

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name","amount", "price", "description"]

main/views.py
from django.shortcuts import render
from .models import Product
from django.http import HttpResponseRedirect
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@login_required(login_url='/login')

def show_main(request):
    products = Product.objects.filter(user=request.user)
    jumlah = Product.objects.filter(user=request.user).count
    
    # Product.objects.count()
    last_login = request.COOKIES.get('last_login', 'No last login information')

    context = {
        'name': request.user.username,
        'products': products,
        'jumlah' : jumlah,
        'last_login': last_login
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk = id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk =id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)


@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

@csrf_exempt
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def increment_amount(request, id):
    product = get_object_or_404(Product, pk=id)
    if product.amount >= 0:
        product.amount += 1
        product.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def decrement_amount(request, id):
    product = get_object_or_404(Product, pk=id)
    if product.amount > 0:
        product.amount -= 1
        product.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def delete_product(request, id):
    product = get_object_or_404(Product, pk=id)
    if product.user == request.user:
        product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))


def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)


def get_product_json(request):
    products = Product.objects.filter(user=request.user)
    product_list = []
    for product in products:
        product_dict = {
            'pk': product.pk,
            'name': product.name,
            'description': product.description,
            'price': product.price,
            'amount': product.amount,
            'edit_url': reverse('main:edit_product', args=[product.pk]),
            'delete_url': reverse('main:delete_product', args=[product.pk]),
        }
        product_list.append(product_dict)
    return JsonResponse(product_list, safe=False)



@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)

    if form.is_valid():
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponse("Created", status=201)
    else:
        # Handle form validation errors and return as JSON
        errors = form.errors.as_json()
        return HttpResponseBadRequest(errors, content_type='application/json')
    return HttpResponseNotFound()


@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
    
    

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}

<style>
    /* Gaya CSS Anda dimulai di sini */
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap");
    *
    {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    
    }
    body
    {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: #fff;
    }

    .box
    {
        position: relative;
        width: 480px;
        height: 500px;
        background: #1c1c1c;
        border-radius: 8px;

    }
    .box form
    {
        color: #fff;
        font-weight: 500;
        text-allign: center;
        letter-spacing: 0.1em;
    }



</style>


<h1>Add New Product</h1>

<body>
    <div class="box">
        <form method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Add Product"/>
                    </td>
                </tr>
            </table>
        </form>
    </div>
<body>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %} 
<!DOCTYPE html>
<html lang="en">

{% comment %} {% block meta %}
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static "CSS/cssloginstyle.css" %}}">
{% endblock meta %}


{% block content %}
{% load static%}

<head>
    <meta charset = "UTF-8">
    <link rel="stylesheet" href="{% static "CSS/cssloginstyle.css" %}}">
</head>
<body>
    <div class="box">
        <form method="POST" action="">
            {% csrf_token %}
            <h2>Log in</h2>
            <div class="inputBox">
                <input type="text" name="username" required>
                <span>Username</span>
                <i></i>
            </div>
            <div class="inputBox">
                <input type="password" name="password">
                <span>Password</span>
                <i></i>
            </div>
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="links">
                <a href="{% url 'main:register' %}">Register</a>
            </div>
            <input type="submit" value="Login">
        </form>
    </div>
</body>
</html>
{% endblock content %} {% endcomment %} 




{% comment %} {% block content %}
<link rel="stylesheet" type="text/css" href="main/style.css">
<body>
    <div class = "login">

        <h1>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <span>Password: </span>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

    </div>
<body>

{% endblock content %}    {% endcomment %}



{% block meta %}
    <title>Login</title>
<style>
    /* Gaya CSS Anda dimulai di sini */
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap");
    *
    {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    
    }
    body
    {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: #fff;
    
    }
    .box
    {
        position: relative;
        width: 380px;
        height: 420px;
        background: #FFFFFF;
        border-radius: 8px;
    }

    .box form
    {
        position: absolute;
        inset: 4px;
        background: #000000;
        padding: 50px 40px;
        border-radius: 8px;
        z-index: 2;
        display: flex;
        flex-direction: column;
    
    }
    
    .box form h2
    {
        color: #fff;
        font-weight: 500;
        text-align: center;
        letter-spacing: 0.1em;
    
    }

    .box form .inputBox
    {
        position: relative;
        width: 300px;
        margin-top: 35px;
    
    }

     
    .box form .inputBox input
    {
        position: relative;
        width: 100%;
        padding: 20px 10px 10px;
        background: transparent;
        outline: none;
        border: none;
        box-shadow: none;
        color: #23242a;
        font-size: 1em;
        letter-spacing: 0.05em;
        transition: 0.5s;
        z-index: 10; 
    }
    
   
    .box form .inputBox span
    {
    
        position: absolute;
        left: 0;
        padding: 20px 10px 10px;
        pointer-events: none;
        color: #8f8f8f;
        font-size: 1em;
        letter-spacing: 0.05em;
        transition: 0.5s;
    }

    .box form .inputBox input:valid ~span,
    .box form .inputBox input:focus ~span

    {
        color: #fff;
        font-size: 0.75em;
        transform: translateY(-34px);
    }
    
    .box form .inputBox i
    {
        position: absolute;
        left: 0;
        bottom: 0;
        width: 100%;
        height:2px ;
        background: #fff;
        border-radius: 4px;
        overflow: hidden;
        transition: 0.5s;
        pointer-events:  none;
    
    } 

    .box form .inputBox input:valid ~i,
    .box form .inputBox input:focus ~i
    {
        height: 44px;

    }

    .box form .links
    {
        display: flex;
        justify-content: space-between;

    }

    .box form .links a
    {
        margin: 10px 0;
        font-size: 0.75em;
        color: #fff;
        text-decoration: none;

    }

</style>
<body>
    <div class="box">
        
        <form method="POST" action="">
            {% csrf_token %}
            <h2>Log in</h2>
            <div class="inputBox">
                <input type="text" name="username" required = "required">
                <span>Username</span>
                <i></i>
            </div>
            <div class="inputBox">
                <input type="password" name="password" required = "required">
                <span>Password</span>
                <i></i>
            </div>
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="links">
                <a href="{% url 'main:register' %}">Register</a>
            </div>
            <input type="submit" value="Login">
        </form>
    </div>
</body>
</html>

{% endblock meta %}



                    

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Page</title>
    <style>
        body {
            font-family: 'Fantasy';
            background-color: #fff;
            margin: 0;
            padding: 0;
            color: black;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            text-align: center;
        }
        
        h1 {
            font-size: 50px;
            margin-bottom: 10px;
        }
        
        h2 {
            font-size: 18px;
            margin-bottom: 5px;
        }
        
        table.product-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        table.product-table th, table.product-table td {
            border: 1px solid white;
            padding: 10px;
            text-align: left;
        }
        
        table.product-table th {
            background-color:#2D2930; 
            color: white;
        }
        
        table.product-table td .amount {
            display: flex;
            align-items: center;
        }
        
        table.product-table td .amount button {
            background-color: #FF5722; 
            color: white;
            border: none;
            padding: 5px 10px;
            margin: 0 5px;
            cursor: pointer;
        }
        
        table.product-table td .amount button:hover {
            background-color: #E64A19; 
        }
        
        table.product-table td .amount span {
            font-weight: bold;
        }
        
        button.delete-button, button.logout-button, button.add-button , button.edit-button{
            background-color: #B71C1C; 
            color: white;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
        }
        
        button.delete-button:hover, button.logout-button:hover, button.add-button:hover, button.edit-button {
            background-color: #7F0000; 
        }

        .navbar {
            background-color: #2D2930;
            overflow: hidden;
        }
        
        .navbar a {
            float: left;
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .navbar a.logout-button {
            float: right; /* Move Logout button to the right */
        }

        .card-container {
            margin-bottom: 1.875rem;
        }

        .card {
            border: 0;
            box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
            -webkit-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
            -moz-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
            -ms-box-shadow: 0px 0px 10px 0px rgba(82, 63, 105, 0.1);
            position: relative;
            display: flex;
            flex-direction: column;
            min-width: 0;
            word-wrap: break-word;
            background-color: #ffffff;
            background-clip: border-box;
            border: 1px solid #e6e4e9;
            border-radius: 8px;
        }

        .card .card-header.no-border {
            border: 0;
        }

        .card .card-header {
            background: none;
            padding: 0 0.9375rem;
            font-weight: 500;
            display: flex;
            align-items: center;
            min-height: 50px;
        }
    
        
    </style>
</head>
<body>
    <div class="navbar">
        <a href="#">{{name}}</a>
        <a href="{% url 'main:logout' %}" class="logout-button">
            Logout
        </a>
    </div>

        <div class="container">
            <h1>Product Information</h1>
            <h3>Set up meja kamu, biar nyaman nugas.</h3>

            <h2>Kamu menyimpan {{ jumlah }} item pada aplikasi ini</h2>

            <div class="card-container" >
                {% for product in products %}
                    <div class="card">
                        <div class="card-header">
                            <h4>{{ product.name }}</h4>
                        </div>
                        <div class="card-body">
                            <p>Rp. {{ product.price }}</p>
                            <p>{{ product.description }}</p>
                            <div class="amount">
                                <a href="{% url 'main:increment_amount' product.id %}">
                                    <button class="inc">+</button>
                                </a>
                                <span>{{ product.amount }}</span>
                                <a href="{% url 'main:decrement_amount' product.id %}">
                                    <button>-</button>
                                </a>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'main:delete_product' product.id %}">
                                <button class="delete-button">Delete</button>
                            </a>
                            <a href="{% url 'main:edit_product' product.pk %}">
                                <button class="edit-button">Edit</button>
                            </a>
                        </div>
                    </div>
                {% endfor %}
                <th> </th>
            </div>

        <a href="{% url 'main:create_product' %}">
            <button class="add-button">Add New Product</button>
        </a>
        <button type="button" class="button is-success" id="addItemButton">
            Add New Item by AJAX
        </button>

        <h5>Sesi terakhir login: {{ last_login }}</h5>
    </div>

</body>


<div class="modal" id="exampleModal"  style="display: none;">
    <div class="modal-background" id="closeModal"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Add New Item</p>
            <button class="delete" aria-label="close" id="cancelButton"></button>
        </header>
        <section class="modal-card-body">
            <form id="form">
                {% csrf_token %}
                <div class="field">
                    <label for="name" class="label">name:</label>
                    <div class="control">
                        <input class="input" type="text" id="name" name="name">
                    </div>
                </div>
                <div class="field">
                    <label for="description" class="label">description:</label>
                    <div class="control">
                        <textarea class="textarea" id="description" name="description"></textarea>
                    </div>
                </div>
                <div class="field">
                    <label for="price" class="label">price:</label>
                    <div class="control">
                        <input class="input" type="number" id="price" name="price">
                    </div>
                </div>
                <div class="field">
                    <label for="amount" class="label">amount:</label>
                    <div class="control">
                        <input class="input" type="number" id="amount" name="amount">
                    </div>
                </div>
            </form>
        </section>
        <footer class="modal-card-foot">
            <button class="button is-success" id="button_add">Add Product</button>
            <button class="button" aria-label="close" id="cancelButton">Cancel</button>
        </footer>
    </div>
</div>


<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json());
    }

    async function refreshProducts() {
        const products = await getProducts();
        let totalProduct = products.length;
        let htmlString = "";
        products.forEach((product, index) => {
            totalTickets += product.amount;
            htmlString += `
            <div class="card-container" >
                {% for product in products %}
                    <div class="card">
                        <div class="card-header">
                            <h4>{{ product.name }}</h4>
                        </div>
                        <div class="card-body">
                            <p>Rp. {{ product.price }}</p>
                            <p>{{ product.description }}</p>
                            <div class="amount">
                                <a href="{% url 'main:increment_amount' product.id %}">
                                    <button class="inc">+</button>
                                </a>
                                <span>{{ product.amount }}</span>
                                <a href="{% url 'main:decrement_amount' product.id %}">
                                    <button>-</button>
                                </a>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'main:delete_product' product.id %}">
                                <button class="delete-button">Delete</button>
                            </a>
                            <a href="{% url 'main:edit_product' product.pk %}">
                                <button class="edit-button">Edit</button>
                            </a>
                        </div>
                    </div>
                {% endfor %}
                <th> </th>
                </div>`;


        });
        document.getElementById("product-count").textContent = totalProduct;
        document.getElementById("product_table").innerHTML = htmlString;
    }

    async function incrementAmount(id) {
        const response = await fetch(`/add-product/${id}`);
        refreshProducts();
    }

    async function decrementAmount(id) {
        const response = await fetch(`/reduce-product/${id}`);
        refreshProducts();
    }

    async function deleteItem(id) {
        const response = await fetch(`/delete-product/${id}`);
        refreshProducts();
    }

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(() => {
            refreshProducts();
            document.getElementById("form").reset(); 
            document.getElementById("exampleModal").classList.remove("is-active");
        });
        return false;
    }

        document.getElementById("button_add").onclick = addProduct;
        
        document.getElementById("addItemButton").onclick = function () {
            document.getElementById("exampleModal").classList.add("is-active");
        };
        
        // Tutup modal saat tombol "Cancel" atau latar belakang modal ditekan.
        document.getElementById("cancelButton").onclick = function () {
            document.getElementById("exampleModal").classList.remove("is-active");
        };
        document.getElementById("closeModal").onclick = function () {
            document.getElementById("exampleModal").classList.remove("is-active");
        };

    
        // Perbarui item saat halaman dimuat.
        refreshProducts();
    </script>

{% endblock content %} 

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}

    <title>Register</title>


{% endblock meta %}


{% block content %}  
<style>
    /* Gaya CSS Anda dimulai di sini */
    @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap");
    *
    {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    
    }
    body
    {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background: #fff;
    }

    .box
    {
        position: relative;
        width: 480px;
        height: 500px;
        background: #1c1c1c;
        border-radius: 8px;

    }
    .box form
    {
        color: #fff;
        font-weight: 500;
        text-align: center;
        letter-spacing: 0.1em;
    }



</style>

<body>
    <div class = "box">
        
        <div class = "login">
    
            <h1>Register</h1>  
        
                <form method="POST" >  
                    {% csrf_token %}  
                    <table>  
                        {{ form.as_table }}  
                        <tr>  
                            <td></td>
                            <td><input type="submit" name="submit" value="Daftar"/></td>  
                        </tr>  
                    </table>  
                </form>
        
            {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
            {% endif %}
        
        </div>   
        
    </div>  
<body>
{% endblock content %} 